import pandas as pd
import numpy as np
#1.	Load all 5 CSV files into separate DataFrames
customers_df=pd.read_csv("customers.csv")
order_items_df=pd.read_csv("order_items.csv")
orders_df=pd.read_csv("orders.csv")
products_df=pd.read_csv("products.csv")
reviews_df=pd.read_csv("reviews.csv")

##2.	Display first 5 rows of each dataset
# print('-----------Display first 5 rows of each dataset------------')
# print('Customer')
# print(customers_df.head())
# print('Order Items')
# print(order_items_df.head())
# print('Order')
# print(orders_df.head())
# print('Products')
# print(products_df.head())
# print('Reviews')
# print(reviews_df.head())

# #3.	Check data types, shape, and basic info
# print('-----------Display basic info------------')
# print('Customer')
# customers_df.info()
# print('Order Items')
# order_items_df.info()
# print('Order')
# orders_df.info()
# print('Products')
# products_df.info()
# print('Reviews')
# reviews_df.info()
# print('-----------Display data types------------')
# print('Customer')
# print(customers_df.dtypes)
# print('Order Items')
# print(order_items_df.dtypes)
# print('Order')
# print(orders_df.dtypes)
# print('Products')
# print(products_df.dtypes)
# print('Reviews')
# print(reviews_df.dtypes)
# print('-----------Display shape------------')
# print('Customer')
# print(customers_df.shape)
# print('Order Items')
# print(order_items_df.shape)
# print('Order')
# print(orders_df.shape)
# print('Products')
# print(products_df.shape)
# print('Reviews')
# print(reviews_df.shape)

# #4.	Identify missing values in each dataset
# print('Identify missing values in each dataset')
# print('Customer')
# print(customers_df.isnull().sum())
# print('Order Items')
# print(order_items_df.isnull().sum())
# print('Order')
# print(orders_df.isnull().sum())
# print('Products')
# print(products_df.isnull().sum())
# print('Reviews')
# print(reviews_df.isnull().sum())

#5.	Find and remove duplicate records
print('Find and remove duplicate records')
print('Customer')
customerDuplicateSum=customers_df.duplicated().sum()
print('Duplicates ',customerDuplicateSum)
if customerDuplicateSum>0:
    customers_df.drop_duplicates(inplace=True)
print('Order Items')
orderItemsDuplicateSum=order_items_df.duplicated().sum()
print('Duplicates ',orderItemsDuplicateSum)
if orderItemsDuplicateSum>0:
    order_items_df.drop_duplicates(inplace=True)
print('Order')
orderDuplicateSum=orders_df.duplicated().sum()
print('Duplicates ',orderDuplicateSum)
if orderDuplicateSum>0:
    orders_df.drop_duplicates(inplace=True)
print('Products')
productDuplicateSum=products_df.duplicated().sum()
print('Duplicates ',productDuplicateSum)
if productDuplicateSum>0:
    products_df.drop_duplicates(inplace=True)
print('Reviews')
reviewDuplicateSum=reviews_df.duplicated().sum()
print('Duplicates ',reviewDuplicateSum)
if reviewDuplicateSum>0:
    reviews_df.drop_duplicates(inplace=True)
##7.	Handle null values appropriately
customers_df.fillna({'city': 'Unknown'}, inplace=True)
orders_df.fillna({'payment_method': 'Unknown'}, inplace=True)
products_df.fillna({'stock_quantity': 0}, inplace=True)
reviews_df.fillna({'review_text': 'Unknown'}, inplace=True)
##6.	Fix data type issues (dates, numbers, etc.)
print("Fix data type issues (dates, numbers, etc.)")
customers_df['registration_date']=pd.to_datetime(customers_df['registration_date'],errors="coerce")
orders_df['order_date']=pd.to_datetime(orders_df['order_date'],errors="coerce")
reviews_df['review_date']=pd.to_datetime(reviews_df['review_date'],errors="coerce")
order_items_df['discount_percent']=order_items_df['discount_percent'].astype('float64')
products_df['stock_quantity']=products_df['stock_quantity'].astype('int64')

#Date range of the data
print('Date range of the data')
print('Customer')
print(f"Date Range : {customers_df['registration_date'].min()} to {customers_df['registration_date'].max()}")
print('Order')
print(f"Date Range : {orders_df['order_date'].min()} to {orders_df['order_date'].max()}")
print('Reviews')
print(f"Date Range : {reviews_df['review_date'].min()} to {reviews_df['review_date'].max()}")